### ISSUE TITLE
npm install ngx-exhaustive-check --save

### ISSUE THREAD

**Issue by sysmat** [soc221b/ngx-exhaustive-check#22]
**Is your feature request related to a problem? Please describe.**

- If this is used only in compile time,  then this lib should be in **devDependencies**

**Describe the solution you'd like**

- `npm install ngx-exhaustive-check --save-dev`

**Describe alternatives you've considered**

**Additional context**

**Comment by soc221b** [comment]
Hi, thank you for pointing it out. 😄 

This package still contributes some "transform" code to the production bundle, for example:

```js
var Nd = (() => {
  let t = class t {
    transform(r, o = []) {
      return r;
    }
  };
  (t.ɵfac = function (o) {
    return new (o || t)();
  }),
    (t.ɵpipe = ki({ name: "ec", type: t, pure: !0, standalone: !0 }));
  let e = t;
  return e;
})();
```

Although this is a small piece of code, eliminating it from the final bundle would be preferable.

Currently, I am unsure if there is a way to eliminate it during compilation. 🤔
